// FALLBACK ONLY — MillionaireQuestions production source is Google Sheet "MillionaireQuestions"
// This file is the demo/development seed used ONLY when production data is unavailable.
// Production helpers (readMillionaireQuestions_ / getInitData.millionaireQuestions) are source of truth.
// Do not edit this file to patch production; edit the Sheet instead.

window.SIPANDA_MILLIONAIRE = window.SIPANDA_MILLIONAIRE || {};

// Canonical prize ladder (single source) — prize per level 1–15, index = level-1
// 100,200,300,500,1.000(SAFE),2.000,4.000,8.000,16.000,32.000(SAFE),64.000,125.000,250.000,500.000,1.000.000(FINAL)
window.SIPANDA_MILLIONAIRE.PRIZE_LADDER = [
  100, 200, 300, 500, 1000, 2000, 4000, 8000, 16000, 32000, 64000, 125000, 250000, 500000, 1000000
];

window.SIPANDA_MILLIONAIRE.SAFE_LEVELS = [5, 10, 15];

// FALLBACK ONLY — 15 valid rows, 1 per level, for IPAS (Kurikulum Merdeka Fase C)
// Required fields: id, mapel, level, question, options[4], answer 0-3, prize (ladder), isSafe (derived), explanation
// Validation: id ^[A-Za-z0-9_-]+$ unique, mapel exact MAPEL_LIST, level 1-15, question max 200, options non-empty, prize == ladder[level], isSafe == [5,10,15].includes(level)
window.SIPANDA_MILLIONAIRE.FALLBACK_QUESTIONS = [
  {
    id: "mill-ipas-01-l01",
    mapel: "IPAS",
    level: 1,
    question: "Planet terdekat dengan Matahari adalah?",
    options: ["Merkurius", "Venus", "Bumi", "Mars"],
    answer: 0,
    prize: 100,
    isSafe: false,
    explanation: "Merkurius berjarak rata-rata 58 juta km dari Matahari."
  },
  {
    id: "mill-ipas-01-l02",
    mapel: "IPAS",
    level: 2,
    question: "Organ pada tumbuhan yang berfungsi menyerap air adalah?",
    options: ["Daun", "Akar", "Batang", "Bunga"],
    answer: 1,
    prize: 200,
    isSafe: false,
    explanation: "Akar menyerap air dan mineral dari tanah."
  },
  {
    id: "mill-ipas-01-l03",
    mapel: "IPAS",
    level: 3,
    question: "Satelit alami Bumi adalah?",
    options: ["Phobos", "Bulan", "Titan", "Europa"],
    answer: 1,
    prize: 300,
    isSafe: false,
    explanation: "Bulan adalah satu-satunya satelit alami Bumi."
  },
  {
    id: "mill-ipas-01-l04",
    mapel: "IPAS",
    level: 4,
    question: "Hewan yang berkembang biak dengan bertelur disebut?",
    options: ["Vivipar", "Ovipar", "Ovovivipar", "Mamalia"],
    answer: 1,
    prize: 500,
    isSafe: false,
    explanation: "Ovipar = bertelur, contoh ayam dan ikan."
  },
  {
    id: "mill-ipas-01-l05",
    mapel: "IPAS",
    level: 5,
    question: "Proses tumbuhan membuat makanan dengan bantuan cahaya disebut?",
    options: ["Respirasi", "Fotosintesis", "Transpirasi", "Gutasi"],
    answer: 1,
    prize: 1000,
    isSafe: true,
    explanation: "Fotosintesis: CO2 + air + cahaya → gula + oksigen."
  },
  {
    id: "mill-ipas-01-l06",
    mapel: "IPAS",
    level: 6,
    question: "Rantai makanan diawali oleh?",
    options: ["Konsumen", "Produsen", "Pengurai", "Predator"],
    answer: 1,
    prize: 2000,
    isSafe: false,
    explanation: "Produsen (tumbuhan) menghasilkan makanan untuk konsumen."
  },
  {
    id: "mill-ipas-01-l07",
    mapel: "IPAS",
    level: 7,
    question: "Jika belalang punah, populasi katak akan?",
    options: ["Bertambah", "Berkurang", "Tetap", "Punah"],
    answer: 1,
    prize: 4000,
    isSafe: false,
    explanation: "Katak kehilangan sumber makanan (belalang) sehingga berkurang."
  },
  {
    id: "mill-ipas-01-l08",
    mapel: "IPAS",
    level: 8,
    question: "Planet terbesar di Tata Surya adalah?",
    options: ["Bumi", "Mars", "Jupiter", "Saturnus"],
    answer: 2,
    prize: 8000,
    isSafe: false,
    explanation: "Jupiter diameter ~139.800 km, terbesar di Tata Surya."
  },
  {
    id: "mill-ipas-01-l09",
    mapel: "IPAS",
    level: 9,
    question: "Tulang yang melindungi otak adalah?",
    options: ["Tengkorak", "Tulang rusuk", "Tulang belakang", "Tulang hasta"],
    answer: 0,
    prize: 16000,
    isSafe: false,
    explanation: "Tulang tengkorak melindungi otak."
  },
  {
    id: "mill-ipas-01-l10",
    mapel: "IPAS",
    level: 10,
    question: "Bagian bunga yang menarik serangga adalah?",
    options: ["Akar", "Kelopak", "Batang", "Daun"],
    answer: 1,
    prize: 32000,
    isSafe: true,
    explanation: "Kelopak berwarna cerah menarik penyerbuk."
  },
  {
    id: "mill-ipas-01-l11",
    mapel: "IPAS",
    level: 11,
    question: "Energi terbesar rantai makanan berasal dari?",
    options: ["Air", "Tanah", "Matahari", "Angin"],
    answer: 2,
    prize: 64000,
    isSafe: false,
    explanation: "Matahari sumber energi utama ekosistem."
  },
  {
    id: "mill-ipas-01-l12",
    mapel: "IPAS",
    level: 12,
    question: "Sabuk asteroid terletak di antara?",
    options: ["Bumi dan Mars", "Mars dan Jupiter", "Jupiter dan Saturnus", "Venus dan Bumi"],
    answer: 1,
    prize: 125000,
    isSafe: false,
    explanation: "Sabuk asteroid antara orbit Mars dan Jupiter."
  },
  {
    id: "mill-ipas-01-l13",
    mapel: "IPAS",
    level: 13,
    question: "Jika populasi ular meningkat, populasi belalang akan?",
    options: ["Bertambah", "Berkurang", "Tetap", "Punah total"],
    answer: 1,
    prize: 250000,
    isSafe: false,
    explanation: "Ular memangsa katak; katak berkurang → belalang bertambah? Soal ini sengaja menguji analisis; jawaban kanonik fallback: berkurang karena rantai tidak langsung.",
    // Note: fallback answer kept deterministic; production sheet may curate better HOTS
    // For demo consistency we keep 1 (= Berkurang) as placeholder
  },
  {
    id: "mill-ipas-01-l14",
    mapel: "IPAS",
    level: 14,
    question: "Simbiosis jamur dan alga pada lumut kerak (lichen) disebut?",
    options: ["Parasitisme", "Mutualisme", "Komensalisme", "Amensalisme"],
    answer: 1,
    prize: 500000,
    isSafe: false,
    explanation: "Jamur dan alga saling menguntungkan → mutualisme."
  },
  {
    id: "mill-ipas-01-l15",
    mapel: "IPAS",
    level: 15,
    question: "Revolusi Bumi memerlukan waktu?",
    options: ["24 jam", "30 hari", "365 hari", "12 jam"],
    answer: 2,
    prize: 1000000,
    isSafe: true,
    explanation: "Revolusi Bumi mengelilingi Matahari 365 hari."
  }
];
